services:
  mysql:
    image: mysql:8.4
    container_name: control-citas-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: control_citas
      MYSQL_USER: citas_user
      MYSQL_PASSWORD: citas_password
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data: